version: '3.6'

volumes:
  database:
  node_modules:

services:
  database:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - database:/var/lib/mysql

  wordpress:
    image: wordpress:6.3.1-php8.0
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress
    restart: always
    ports:
      - ${PORT_WORDPRESS}:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 0
      WORDPRESS_TABLE_PREFIX: klg_
      WORDPRESS_CONFIG_EXTRA: define('FS_METHOD', 'direct');
    volumes:
      - ./docker/config/php:/etc/php/conf.d:ro,cached
      - ./docker/logs/apache2:/var/log/apache2
      - ./plugins:/var/www/html/plugins
      - ${WORDPRESS_THEME_LOCATION}:/var/www/html/wp-content/themes/${WORDPRESS_THEME_NAME}:ro,cached
      - ./docker/volumes/wordpress/wp-content:/var/www/html/wp-content:cached
      - ./:/var/www/html/wp-content
      - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini

    depends_on:
      - database

  adminer:
    image: adminer:latest
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    restart: always
    ports:
      - ${PORT_ADMINER}:8080
    links:
      - database
    depends_on:
      - database

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    restart: always
    ports:
      - ${PORT_PHPMYADMIN}:80
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_ABSOLUTE_URI: http://${DOMAIN}/_pma/
      PMA_HOST: database
    links:
      - database
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/logs/nginx:/var/log/nginx
    depends_on:
      - wordpress
      - adminer
      - phpmyadmin

  composer:
    image: composer:latest
    container_name: ${COMPOSE_PROJECT_NAME}_composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ${WORDPRESS_THEME_LOCATION}:/var/www/html/theme
    depends_on:
      - wordpress

  wpcli:
    image: wordpress:cli
    container_name: ${COMPOSE_PROJECT_NAME}_wpcli
    working_dir: /var/www/html
    user: xfs
    volumes_from:
      - wordpress
    links:
      - database
      - wordpress
    depends_on:
      - database
      - wordpress

#  TODO node + gulp + browsersync on docker
#  node:
#    build:
#      context: ./docker
#      dockerfile: node-dockerfile
#    image: mohito_node
#    container_name: ${COMPOSE_PROJECT_NAME}_node
#    working_dir: /var/www/html
#    ports:
#      - ${PORT_GULP}:3000
#    volumes:
#      - ${GULP_SRC_LOCATION}:/var/www/html
#      - ${GULP_THEME_LOCATION}:/var/www/theme
#      - node_modules:/var/www/html/node_modules
#    depends_on:
#      - wordpress
#      - nginx
